coolsite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('opapp/', include('opinion.urls', namespace='opinion')),
    path('admin/', admin.site.urls),
]

opinion/urls.py
from django.urls import path

from . import views

app_name = 'opinion'

urlpatterns = [
    path('', views.list_all, name='list_all'),
    path('', views.list_all, name='index'),
    path('<int:opinion_id>/', views.show_opinion, name='show_opinion'),
    path('item/<int:item_id>/add_opinion/', views.add_opinion, name='add_opinion'),
    path('<int:opinion_id>/edit/', views.edit_opinion, name='edit_opinion'),
    path('<str:table>/add/', views.add_category_or_item, name='add_category_or_item'),
    path('delete/', views.delete_opinion, name='delete_opinion'),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
]

opinion/models.py
from django.db import models


class Category(models.Model):
    name_text = models.CharField(max_length=100, unique=True)
    description_text = models.CharField(max_length=200)

    def __str__(self):
        return self.name_text


class Item(models.Model):
    PRODUCT = 'product'
    SERVICE = 'service'
    TYPE_CHOICES = (
        (PRODUCT, 'Product'),
        (SERVICE, 'Service'),
        ('', 'Select type'),
    )
    name_text = models.CharField(max_length=100, unique=True)
    description_text = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='items')
    type_text = models.CharField(max_length=7, choices=TYPE_CHOICES)
    opinions_number = models.IntegerField(default=0)

    def __str__(self):
        return self.name_text


class Opinion(models.Model):
    title_text = models.CharField(max_length=100)
    message_text = models.TextField(max_length=500)
    publish_date = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='opinions')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='opinions')

    def __str__(self):
        return self.title_text

    class Meta:
        ordering = ('-publish_date',)

pages/models.py
from django.db import models

# Create your models here.

opinion/forms.py
from django.forms import ModelForm
from .models import Opinion, Category, Item


class OpinionForm(ModelForm):
    class Meta:
        model = Opinion
        fields = ('item', 'title_text', 'message_text')
        labels = {
            'title_text': 'Title',
            'message_text': 'Message',
        }


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ('name_text', 'description_text')
        labels = {
            'name_text': 'Name',
            'description_text': 'Description',
        }


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ('name_text', 'description_text', 'category', 'type_text')
        labels = {
            'name_text': 'Name',
            'description_text': 'Description',
            'category': 'Category',
            'type_text': 'Type'
        }

opinion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import HiddenInput
from django.http import HttpResponseNotFound
import opinion.data_handler as dh
from .models import Opinion, Item
from .forms import OpinionForm

TABLES = ['category', 'item']


def list_all(request):
    category_id = request.GET.get('filter', 1)
    context = dh.prepare_list(category_id)

    return render(request, 'opinion/list_all.html', context)


def show_opinion(request, opinion_id):
    opinion = get_object_or_404(Opinion, id=opinion_id)
    context = {'opinion': opinion}
    context.update(dh.prepare_list())
    return render(request, 'opinion/show_opinion.html', context)


def add_opinion(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    opinion = Opinion(item=item, category=item.category)
    if request.method == 'POST':
        render_target = dh.save_opinion(opinion, request)
    else:
        form = OpinionForm(instance=opinion)
        form.fields['item'].queryset = Item.objects.filter(category_id=item.category_id)
        context = {'form': form, 'table': 'opinion',
                   'action_url': 'opinion:add_opinion', 'action_arg': item_id}
        context.update(dh.prepare_list())
        render_target = render(request, 'opinion/add_form.html', context)

    return render_target


def edit_opinion(request, opinion_id):
    opinion = get_object_or_404(Opinion, id=opinion_id)
    if request.method == 'POST':
        render_target = dh.save_opinion(opinion, request)
    else:
        form = OpinionForm(instance=opinion)
        form.fields['item'].widget = HiddenInput()
        context = {'form': form, 'opinion_id': opinion_id, 'item_name': opinion.item.name_text}
        context.update(dh.prepare_list())
        render_target = render(request, 'opinion/edit_opinion.html', context)

    return render_target


def add_category_or_item(request, table):
    if table not in TABLES:
        HttpResponseNotFound('<p><Wrong URL/p>')
    render_target = dh.save_category_or_item(request, table)

    return render_target


def delete_opinion(request):
    if request.method == 'POST':
        dh.delete_record(request.POST['op_id'])

    return redirect('opinion:list_all')

pages/views.py
from django.shortcuts import render
from coolsite.settings import COOLSITE_APPS


def index(request):
    apps = [app.split('.')[0] for app in COOLSITE_APPS]
    context = {'apps_list': apps}

    return render(request, 'pages/index.html', context)

coolsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Opinions sharing{% endblock %}</title>
  <meta name="description" content="Simple CRUD django example">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'opinion:index' %}">CoolSite</a>
          </div>
          <ul class="nav navbar-nav">
            <li><a href="{% url 'opinion:add_category_or_item' table='category' %}">Add new category</a></li>
            <li><a href="{% url 'opinion:add_category_or_item' table='item' %}">Add new product or service</a></li>
          </ul>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2">
      <a href="{% url 'opinion:index' %}" class="btn btn-primary btn-block">Opinions sharing</a><br>
      <ul class="nav nav-pills nav-stacked" role="tablist">
        {% block left_nav %}{% endblock %}
      </ul>
    </div>
    <div class="col-lg-10">
      {% block center %}{% endblock %}
    </div>
  </div>
</div>
</body>
</html>

opinion/templates/opinion/add_form.html
{% extends 'base.html' %}
{% block left_nav %}
 {% include 'opinion/categories_list.html' %}
{% endblock %}

{% block center %}

{% if table == 'item' %}
    <h1>Add new item (product or service)</h1>
{% elif table == 'category' %}
    <h1>Add new category</h1>
{% elif table == 'opinion' %}
    <h1>You may choose another item from the same category</h1>
{% endif %}

{% if form.errors %}
    <p>Form validation failed with {{ form.errors }}</p>
{% endif%}

<form action="{% url action_url action_arg %}" method="post">
  {% csrf_token %}
  <table class="form-group">{{ form.as_table }}</table>
  <button type="submit" class="btn btn-default">Add</button>
</form>

{%  endblock %}

opinion/templates/opinion/categories_list.html
  <h4>List of categories</h4>
  {% for cat in categories %}
    <li {{ highlight }}><a href="{% url 'opinion:list_all' %}?filter={{ cat.id }}">{{ cat.name_text }}</a></li>
  {% endfor %}

opinion/templates/opinion/edit_opinion.html
{% extends 'base.html' %}
{% load static %}
{% block center %}

<h1>Edit opinion about {{ item_name }}</h1>

{% if form.errors %}
    <p>Form validation failed with {{ form.errors }}</p>
{% endif%}

<form action="{% url 'opinion:edit_opinion' opinion_id%}" method="post">
    {% csrf_token %}
    <table class="form-table">{{ form.as_table }}</table>
    <input type="submit" value="Update">
</form>

{%  endblock %}

opinion/templates/opinion/list_all.html
{% extends 'base.html' %}
{% load static %}
{% block left_nav %}
 {% include 'opinion/categories_list.html' %}
{% endblock %}

{% block center %}
  <div class="panel-group" id="accordion">
    {% if not category_selected %}
      <h4>Please, select a category on the left</h4>
    {% endif %}
    {% for item in category_selected.items.all %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}">
              {{ item.name_text }}</a>
            <span title="Opinions counter" class="badge">{{ item.opinions_number }}</span>
            <a href="{%  url 'opinion:add_opinion' item_id=item.id %}" title="Add new opinion">
                          <img src="{% static 'images/add-16.png' %}"></a>
          </h4>
        </div>
        <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
          <div class="panel-body">
            <ul>
              {% for opinion in item.opinions.all %}
                <li>
                  <a href="{% url 'opinion:show_opinion' opinion.id %}">{{ opinion.title_text }}</a>
                  <p>Published: {{ opinion.publish_date }}</p>
                </li>
              {%  endfor %}
            </ul>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

opinion/templates/opinion/show_opinion.html
{% extends 'base.html' %}
{% block left_nav %}
 {% include 'opinion/categories_list.html' %}
{% endblock %}

{% block center %}
    This is opinion about {{ opinion.item.type_text }} <em>{{ opinion.item }}</em> in category {{ opinion.category }}
    <p><strong>{{ opinion.title_text }}</strong></p>
    <hr>
    <p>{{ opinion.message_text }}</p>
    <hr>
    <table>
    <tr>
        <td>
            <form action="{% url 'opinion:delete_opinion' %}" method="post">
            {% csrf_token %}
            <input name="op_id" type="hidden" value="{{ opinion.id }}">
            <input type="submit" value="Delete this opinion">
            </form>
        </td>
        <td>
            <form action="{% url 'opinion:edit_opinion' opinion.id %}" method="get">
            <input type="submit" value="Edit this opinion">
            </form>
        </td>
    </tr>
</table>
{% endblock %}

pages/templates/pages/index.html
{%  extends 'base.html' %}
{%  block center %}
    <p>This is a list of user applications in current Django project</p>
<ul>
    {% for app in apps_list %}
        <li><a href="{% url app|add:':index' %}">{{ app|capfirst }} App</a></li>
    {% endfor %}
</ul>
{%  endblock %}